<a href="https://colab.research.google.com/github/cow-coding/ML-DL-Study/blob/master/Deep%20Learning%20PyTorch/1.Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import library

In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

# Basic tensor

## Scalar

일반적으로 알고 있는 상수값

In [ ]:
scalar1 = torch.tensor([1.])
print(scalar1)

scalar2 = torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


In [ ]:
add_scalar = scalar1 + scalar2
display(torch.add(scalar1, scalar2))
add_scalar

tensor([4.])

tensor([4.])

In [ ]:
sub_scalar = scalar1 - scalar2
display(torch.sub(scalar2, scalar2))
sub_scalar

tensor([0.])

tensor([-2.])

In [ ]:
mul_scalar = scalar1 * scalar2
display(torch.mul(scalar1, scalar2))
mul_scalar

tensor([3.])

tensor([3.])

In [ ]:
div_scalar = scalar1 / scalar2
display(torch.div(scalar1, scalar2))
div_scalar

tensor([0.3333])

tensor([0.3333])

## Vector

하나의 값을 2개 이상의 수치로 표현한 것

In [ ]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


벡터의 산술연산은 요소별(element-wise)로 수행

In [ ]:
add_vector = vector1 + vector2
display(torch.add(vector1, vector2))
add_vector

tensor([5., 7., 9.])

tensor([5., 7., 9.])

In [ ]:
sub_vector = vector1 - vector2
display(torch.sub(vector1, vector2))
sub_vector

tensor([-3., -3., -3.])

tensor([-3., -3., -3.])

In [ ]:
mul_vector = vector1 * vector2
display(torch.mul(vector1, vector2))
mul_vector

tensor([ 4., 10., 18.])

tensor([ 4., 10., 18.])

In [ ]:
div_vector = vector1 / vector2
display(torch.div(vector1, vector2))
div_vector

tensor([0.2500, 0.4000, 0.5000])

tensor([0.2500, 0.4000, 0.5000])

In [ ]:
torch.dot(vector1, vector2)

tensor(32.)

vector의 내적값

## Matrix

2개 이상의 벡터 값으로 구선된 값
선형 대수의 기본단위

In [ ]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
matrix1

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
matrix2 = torch.tensor([[5., 6.],[7., 8.]])
matrix2

tensor([[5., 6.],
        [7., 8.]])

In [ ]:
sum_matrix = matrix1 + matrix2
display(torch.add(matrix1, matrix2))
sum_matrix

tensor([[ 6.,  8.],
        [10., 12.]])

tensor([[ 6.,  8.],
        [10., 12.]])

In [ ]:
sub_matrix = matrix1 - matrix2
display(torch.sub(matrix1, matrix2))
sub_matrix

tensor([[-4., -4.],
        [-4., -4.]])

tensor([[-4., -4.],
        [-4., -4.]])

In [ ]:
mul_matrix = matrix1 * matrix2
display(torch.mul(matrix1, matrix2))
mul_matrix

tensor([[ 5., 12.],
        [21., 32.]])

tensor([[ 5., 12.],
        [21., 32.]])

In [ ]:
div_matrix = matrix1 / matrix2
display(torch.div(matrix1, matrix2))
div_matrix

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [ ]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

`torch.mul()`은 각 원소별 곱을 구하는 것이다.
우리가 아는 행렬 곱 연산은 `torch.matmul()`로 계산한다.

## Tensor

2차원 이상의 배열을 텐서라고 한다.

In [ ]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
tensor1

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [ ]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
tensor2

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])

In [ ]:
sum_tensor = tensor1 + tensor2
display(torch.add(tensor1, tensor2))
sum_tensor

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [ ]:
sub_tensor = tensor1 - tensor2
display(torch.sub(tensor1, tensor2))
sub_tensor

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [ ]:
mul_tensor = tensor1 * tensor2
display(torch.mul(tensor1, tensor2))
mul_tensor

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [ ]:
div_tensor = tensor1 / tensor2
display(torch.div(tensor1, tensor2))
div_tensor

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

# Autograd

back propagation으로 파라미터를 업데이트하는 방법으로 autograd방식을 사용한다.  


## Setting

In [ ]:
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

`BATCH_SIZE` : 파라미터를 업데이트할 때 계산되는 데이터의 개수, 이 크기에 맞춰 output을 계산하고 오찻값을 계산. input으로 이용되는 데이터가 64개라는 의미  

`INPUT_SIZE` : 입력층의 노드 수, 전체 Input의 크기를 의미함. `INPUT_SIZE`크기의 벡터 값을 `BATCH_SIZE`개만큼 사용한다는 의미  

`HIDDEN_SIZE` : 은닉층의 노드 수  
`OUTPUT_SIZE` : 최종 출력 벡터 크기

## 

In [ ]:
x = torch.randn(BATCH_SIZE,
                INPUT_SIZE,
                device = device,
                dtype = torch.float,
                requires_grad = False)

y = torch.randn(BATCH_SIZE,
                OUTPUT_SIZE,
                device = device,
                dtype = torch.float,
                requires_grad = False)

w1 = torch.randn(INPUT_SIZE,
                 HIDDEN_SIZE,
                 device = device,
                 dtype = torch.float,
                 requires_grad = True)

w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE,
                 device = device,
                 dtype = torch.float,
                 requires_grad = True)

gradient 계산은 가중치(weight)에 대해서 진행하는 것이므로 Input과 Output인 x와 y에는 적용하지 않는다.  
`require_grad = False`로 설정하면 해당 값은 gradient를 계산하지 않는다.

In [ ]:
learning_rate = 1e-6

for t in range(1, 501):
  y_pred = x.mm(w1).clamp(min = 0).mm(w2)
  loss = (y_pred - y).pow(2).sum()

  if t % 100 == 0:
    print('Iteration: ', t, '\t', 'Loss: ', loss.item())
    
  loss.backward()

  with torch.no_grad():
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad

    w1.grad.zero_()
    w2.grad.zero_()

Iteration:  100 	 Loss:  581.0009765625
Iteration:  200 	 Loss:  2.449338912963867
Iteration:  300 	 Loss:  0.02515566535294056
Iteration:  400 	 Loss:  0.0006018607527948916
Iteration:  500 	 Loss:  7.998217188287526e-05
