<a href="https://colab.research.google.com/github/cow-coding/ML-DL-Study/blob/master/%EC%83%9D%ED%99%9C%EC%BD%94%EB%94%A9_%EC%BD%94%EB%94%A9%EC%95%BC%ED%95%99/appendix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 학습이 잘 되는 모뎅
- 사용할 레이어
  - tf.keras.layers.BatchNormalization()
  - tf.keras.layers.Activation('swish')
- 데이터
  - 보스턴 집값: 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  - 아이리스 품종: 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

In [ ]:
# library
import tensorflow as tf
import pandas as pd

In [ ]:
# past data
url =  'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(url)

cause = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
effect = boston[['medv']]

print(cause.shape, effect.shape)

(506, 13) (506, 1)


In [ ]:
# model making

X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# model fitting
model.fit(cause, effect, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 2ms/step - loss: 589.1776
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 582.1537
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 577.4327
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 572.2398
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 567.3403
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 563.7647
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 559.1107
Epoch 8/1000
16/16 [==============================] - 0s 1ms/step - loss: 554.4405
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 550.3085
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 545.5233
Epoch 11/1000
16/16 [==============================] - 0s 1ms/step - loss: 540.7242
Epoch 12/1000
16/16 [==============================] - 0s 2ms/step - loss: 536.2326
E

In [ ]:
print(model.predict(cause[0:5]))
print(effect[0:5])

[[26.223984]
 [24.00534 ]
 [33.596123]
 [32.32614 ]
 [34.013134]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종

In [ ]:
url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(url)
iris = pd.get_dummies(iris)

cause = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
effect = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(cause.shape, effect.shape)

(150, 4) (150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
model.fit(cause, effect, epochs=1000, batch_size=150)

In [ ]:
print(model.predict(cause[0:5]))
print(effect[0:5])

[[9.9997842e-01 2.4387311e-06 1.9200077e-05]
 [9.9997699e-01 2.4741996e-06 2.0467760e-05]
 [9.9996901e-01 2.6845212e-06 2.8202916e-05]
 [9.9999464e-01 1.4783428e-06 3.8979506e-06]
 [9.9998569e-01 2.0486011e-06 1.2227911e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
