<a href="https://colab.research.google.com/github/cow-coding/ML-DL-Study/blob/master/%EC%83%9D%ED%99%9C%EC%BD%94%EB%94%A9_%EC%BD%94%EB%94%A9%EC%95%BC%ED%95%99/%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
boston : 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
iris : 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

In [ ]:
# library
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [ ]:
# setting
url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(url)

cause = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
effect = boston[['medv']]

print(cause.shape, effect.shape)

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

(506, 13) (506, 1)


In [ ]:
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_13 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_14 (Dense)             (None, 3)                 33        
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 4         
Total params: 177
Trainable params: 177
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# fitting
model.fit(cause, effect, epochs=1000, verbose=0)
model.fit(cause, effect, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 947us/step - loss: 9.2407
Epoch 2/10
16/16 [==============================] - 0s 916us/step - loss: 10.4705
Epoch 3/10
16/16 [==============================] - 0s 962us/step - loss: 11.1880
Epoch 4/10
16/16 [==============================] - 0s 937us/step - loss: 9.6145
Epoch 5/10
16/16 [==============================] - 0s 932us/step - loss: 9.9097
Epoch 6/10
16/16 [==============================] - 0s 811us/step - loss: 9.4009
Epoch 7/10
16/16 [==============================] - 0s 937us/step - loss: 9.7135
Epoch 8/10
16/16 [==============================] - 0s 846us/step - loss: 9.3619
Epoch 9/10
16/16 [==============================] - 0s 826us/step - loss: 10.1273
Epoch 10/10
16/16 [==============================] - 0s 820us/step - loss: 9.5979


In [ ]:
# use model
print(model.predict(cause[:5]))
print(effect[:5])

[[29.481722]
 [23.027624]
 [34.766857]
 [33.16109 ]
 [31.806032]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [ ]:
# setting
url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(url)
iris = pd.get_dummies(iris)

cause = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
effect = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(cause.shape, effect.shape)

(150, 4) (150, 3)


In [ ]:
# model make
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# mode fitting
model.fit(cause, effect, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1471 - accuracy: 0.9800
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1484 - accuracy: 0.9667
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1424 - accuracy: 0.9800
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1416 - accuracy: 0.9800
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1358 - accuracy: 0.9733
Epoch 6/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1329 - accuracy: 0.9800
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1352 - accuracy: 0.9667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1333 - accuracy: 0.9800
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1267 - accuracy: 0.9800
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1247 - accuracy: 0.9800
Epoch 11/100
5/5 [===========

In [ ]:
# model use
print(model.predict(cause[0:5]))
print(effect[0:5])

[[9.9732471e-01 2.6446767e-03 3.0503830e-05]
 [9.9713516e-01 2.8370488e-03 2.7824788e-05]
 [9.9737203e-01 2.5861894e-03 4.1718478e-05]
 [9.9727482e-01 2.6929281e-03 3.2274540e-05]
 [9.9742174e-01 2.5436229e-03 3.4612043e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
